version: '3'

services:
  yu-poa1:
    container_name: yu-poa1
    image: zhengjianhui/yu-poa:latest
    restart: always
    privileged: true
    ports:
      - 7999:7999
      - 8999:8999
    volumes:
      - ./config/node_1.toml:/go/chain/node.toml
    networks:
      yu-net:
        ipv4_address: 172.16.0.11
    command: ./yu-poa -idx=0 -k=/go/chain/node.toml

  yu-poa2:
    container_name: yu-poa2
    image: zhengjianhui/yu-poa:latest
    restart: always
    privileged: true
    ports:
      - 7998:7999
      - 8998:8999
    volumes:
      - ./config/node_2.toml:/go/chain/node.toml
    networks:
      yu-net:
        ipv4_address: 172.16.0.12
    depends_on:
      - yu-poa1
    command: ./yu-poa -idx=1 -k=/go/chain/node.toml

  yu-poa3:
    container_name: yu-poa3
    image: zhengjianhui/yu-poa:latest
    restart: always
    privileged: true
    ports:
      - 7997:7999
      - 8997:8999
    volumes:
      - ./config/node_3.toml:/go/chain/node.toml
    networks:
      yu-net:
        ipv4_address: 172.16.0.13
    depends_on:
      - yu-poa1
    command: ./yu-poa -idx=2 -k=/go/chain/node.toml

networks:
  yu-net:
    ipam:
      config:
      - subnet: 172.16.0.0/24
