run_mode = 0
http_port = "7999"
ws_port = "8999"
log_level = "info"
lei_limit = 50000
timeout = 60

[block_chain.chain_db]
sql_db_type = "sqlite"
dsn = "chain.db"

[yu_db.base_db]
sql_db_type = "sqlite"
dsn = "yudb.db"

[txpool]
pool_size = 2048
txn_max_size = 1024000

[state.kv.index_db]
kv_type = "bolt"
path = "./state_index.db"

[state.kv.node_base]
kv_type = "bolt"
path = "./state_base.db"

[p2p]
p2p_listen_addrs = [
    "/ip4/0.0.0.0/tcp/8887",
]
protocol_id = "yu"
node_key_type = 1
node_key_rand_seed = 1
